CREATE TABLE occ_dev.m_location (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  active_from DATE,
  active_to DATE,
  location_type_id NUMBER,
  address1 VARCHAR2(256 BYTE),
  address2 VARCHAR2(256 BYTE),
  city VARCHAR2(256 BYTE),
  "STATE" VARCHAR2(256 BYTE),
  contact_email VARCHAR2(256 BYTE),
  contact_name VARCHAR2(256 BYTE),
  contact_phone VARCHAR2(256 BYTE),
  code VARCHAR2(256 BYTE),
  "CAPACITY" NUMBER,
  zipcode VARCHAR2(256 BYTE),
  additional_info VARCHAR2(4000 BYTE),
  parent_id NUMBER,
  created_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  "VERSION" NUMBER,
  is_active CHAR(256 BYTE) DEFAULT 1 NOT NULL,
  country VARCHAR2(256 BYTE),
  "NAME" VARCHAR2(256 BYTE),
  location_timezone VARCHAR2(256 BYTE),
  location_order NUMBER,
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  CONSTRAINT m_location_id_pk PRIMARY KEY ("ID"),
  CONSTRAINT m_location_uk UNIQUE (unique_id),
  CONSTRAINT m_location_parent_id_fk FOREIGN KEY (location_type_id) REFERENCES occ_dev.m_location_type ("ID")
);