CREATE TABLE occ_dev.m_lookup_value (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  code VARCHAR2(256 BYTE),
  "VALUE" VARCHAR2(256 BYTE),
  active_from TIMESTAMP,
  active_to TIMESTAMP,
  lookup_type_id NUMBER,
  created_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  "VERSION" NUMBER,
  sort_order NUMBER,
  is_default CHAR(256 BYTE),
  description CLOB,
  criteria CLOB,
  location_id NUMBER,
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  is_active CHAR(256 BYTE) DEFAULT 1 NOT NULL,
  CONSTRAINT m_lookup_value_pk PRIMARY KEY ("ID"),
  CONSTRAINT m_lookup_value_uk UNIQUE (unique_id),
  CONSTRAINT m_location_id_fk FOREIGN KEY (location_id) REFERENCES occ_dev.m_location ("ID"),
  CONSTRAINT m_lookup_type_id_fk FOREIGN KEY (lookup_type_id) REFERENCES occ_dev.m_lookup_type ("ID")
);