CREATE TABLE occ_dev.t_audio_visual (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  created_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  audio_visual_link VARCHAR2(256 BYTE),
  audio_visual_notes VARCHAR2(256 BYTE),
  trigger_notification NUMBER,
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  event_id NUMBER,
  "VERSION" NUMBER,
  dial_in_number VARCHAR2(256 BYTE),
  conference_id VARCHAR2(256 BYTE),
  security_pin VARCHAR2(256 BYTE),
  webex_link VARCHAR2(256 BYTE),
  webex_start_time TIMESTAMP,
  zoom_link VARCHAR2(256 BYTE),
  zoom_start_time TIMESTAMP,
  video_start_time TIMESTAMP,
  "OTHER" VARCHAR2(256 BYTE),
  web_cast_start_time TIMESTAMP,
  CONSTRAINT t_audio_visual_pk PRIMARY KEY ("ID"),
  CONSTRAINT t_audio_visual_uk UNIQUE (unique_id),
  CONSTRAINT t_audio_visual_event_id_fk FOREIGN KEY (event_id) REFERENCES occ_dev.t_cust_event ("ID")
);