CREATE TABLE occ_dev.t_cust_event_day_catering (
  "ID" NUMBER NOT NULL,
  event_day_id NUMBER,
  duration NUMBER,
  room NUMBER,
  catering_type VARCHAR2(256 BYTE),
  no_of_attendees NUMBER,
  diet_information VARCHAR2(256 BYTE),
  notes VARCHAR2(4000 BYTE),
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  created_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  "VERSION" NUMBER,
  activity_start_time TIMESTAMP,
  event_id NUMBER,
  activity_date DATE,
  trigger_notification NUMBER,
  cost_center VARCHAR2(256 BYTE),
  cost_center_country VARCHAR2(256 BYTE),
  cost_center_manager_email VARCHAR2(256 BYTE),
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  CONSTRAINT t_cust_event_day_cat_pk PRIMARY KEY ("ID"),
  CONSTRAINT t_cust_event_day_catering_uk UNIQUE (unique_id),
  CONSTRAINT t_cust_event_day_cat_event_fk FOREIGN KEY (event_id) REFERENCES occ_dev.t_cust_event ("ID"),
  CONSTRAINT t_cust_event_day_cat_ev_day_fk FOREIGN KEY (event_day_id) REFERENCES occ_dev.t_cust_event_day ("ID")
);