CREATE TABLE occ_dev.t_cust_event_day_room (
  "ID" NUMBER NOT NULL,
  event_day_id NUMBER,
  room NUMBER,
  room_type VARCHAR2(256 BYTE),
  room_start_time TIMESTAMP,
  room_end_time TIMESTAMP,
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  session_title VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  created_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  event_id NUMBER,
  main_room_notes VARCHAR2(256 BYTE),
  no_of_attendees VARCHAR2(256 BYTE),
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  configuration_type VARCHAR2(256 BYTE),
  CONSTRAINT t_cust_event_day_rm_pk PRIMARY KEY ("ID"),
  CONSTRAINT t_cust_event_day_room_uk UNIQUE (unique_id),
  CONSTRAINT t_cust_event_day_rm_event_fk FOREIGN KEY (event_id) REFERENCES occ_dev.t_cust_event ("ID"),
  CONSTRAINT t_cust_event_day_rm_ev_day_fk FOREIGN KEY (event_day_id) REFERENCES occ_dev.t_cust_event_day ("ID")
);