CREATE TABLE occ_dev.t_oauth_session (
  "ID" NUMBER(11) NOT NULL,
  unique_id VARCHAR2(4000 BYTE) NOT NULL,
  account_id NUMBER(11),
  session_token VARCHAR2(256 BYTE),
  expires_at TIMESTAMP,
  auth_code VARCHAR2(256 BYTE),
  auth_code_expires_at TIMESTAMP,
  redirect_uri VARCHAR2(256 BYTE),
  refresh_token_id NUMBER(11),
  created_at TIMESTAMP NOT NULL DISABLE,
  created_by VARCHAR2(256 BYTE) NOT NULL DISABLE,
  updated_at TIMESTAMP NOT NULL DISABLE,
  updated_by VARCHAR2(256 BYTE) NOT NULL DISABLE,
  oauth_provider_id NUMBER(11),
  idx_token VARCHAR2(8 BYTE) NOT NULL DISABLE,
  aws_region VARCHAR2(256 BYTE),
  CONSTRAINT t_oauth_session_pk PRIMARY KEY ("ID"),
  CONSTRAINT t_oauth_session_uk UNIQUE (unique_id),
  CONSTRAINT t_oauth_session_acc_id_fk FOREIGN KEY (account_id) REFERENCES occ_dev.m_user ("ID")
);