CREATE TABLE occ_dev.t_upload_line (
  "ID" NUMBER(20) NOT NULL,
  unique_id VARCHAR2(256 BYTE) NOT NULL,
  upload_header_id NUMBER(20),
  content_type VARCHAR2(256 BYTE),
  file_size NUMBER(20),
  file_name VARCHAR2(256 BYTE),
  upload_location VARCHAR2(256 BYTE),
  document_original_name VARCHAR2(256 BYTE),
  document_category VARCHAR2(256 BYTE),
  document_remote_name VARCHAR2(256 BYTE),
  document_description VARCHAR2(256 BYTE),
  additional_info VARCHAR2(2048 BYTE),
  created_by VARCHAR2(256 BYTE) NOT NULL,
  updated_by VARCHAR2(256 BYTE) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  "VERSION" NUMBER(6),
  idx_token VARCHAR2(4 BYTE) NOT NULL,
  "DOCUMENT" BLOB,
  CONSTRAINT t_upload_line_pk PRIMARY KEY ("ID"),
  CONSTRAINT t_upload_line_uk UNIQUE (unique_id),
  CONSTRAINT t_upload_line_ul_head_id_fk FOREIGN KEY (upload_header_id) REFERENCES occ_dev.t_upload_header ("ID")
);